### PR TITLE
Publish base image to quay.io via CI

### PR DESCRIPTION
**Pull request by kian**
Use CircleCI to build and publish the placelocal-base-image.

### CODE REVIEW

**Comment by kian** [comment]
@nathanial @chadq @d3ming

**Comment by kian** [comment]
I created a robot account in Quay and set the necessary environment variables within this project on CircleCI.  Note we currently only publish the master branch builds.

**Comment by d3ming** [comment]
Nice, 👍

**Comment by nathanial** [comment]
💯

**Pull request merged**
